media: src/assets
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/blog
    filename: '{primary}/index.mdx'
    view:
      fields: [title, date]
      primary: title
      sort: [date, title]
      default:
        search: ''
        sort: date
        order: desc
    fields:
      - { name: title, label: Title, type: string, required: true }
      - {
          name: description,
          label: Descirption,
          type: string,
          options: { maxlength: 160 },
        }
      - { name: date, label: Publish Date, type: date, required: true }
      - { name: order, label: Order, type: number }
      - { name: authors, label: Author, type: string, list: true }
      - { name: image, label: Hero Image, type: image }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: body, label: Body, type: rich-text }
      - { name: draft, label: Draft, type: boolean, default: false }
  - name: social
    label: Social Links
    type: file
    path: src/consts.ts
    list: true
    fields:
      - name: name
        label: Name
        type: string
      - name: icon
        label: Icon
        type: string
      - name: href
        label: HREF
        type: string
